spring:
  config:
    activate:
      on-profile: "prod"

build:
  version: "1.0"

accounts:
  message: "Banking Application inside PROD Environment"
  contactDetails:
    name: "Aishwarya Rajesh - Product Owner"
    email: "aishwarya.rajesh@bank.com"
  onCallSupport:
    - (080)121-7890
    - (080)122-6703