services:
    accounts:
      image: sushmithanat/accounts:s4
      container_name: svc-accounts-ms
      ports:
        - "8080:8080"
      deploy:
        resources:
          limits:
            memory: 700m
      networks:
        - banking
    loans:
      image: sushmithanat/loans:s4
      container_name: svc-loans-ms
      ports:
        - "8090:8090"
      deploy:
        resources:
          limits:
            memory: 700m
      networks:
        - banking
    cards:
      image: sushmithanat/cards:s4
      container_name: svc-cards-ms
      ports:
        - "9000:9000"
      deploy:
        resources:
          limits:
            memory: 700m
      networks:
        - banking
networks:
  banking:
    driver: "bridge"